services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: marketdb
#    volumes:
#      - postgres_data:/var/lib/postgresql/data # Persist data in a named volume
    ports:
      - "5432:5432"
  shopfront:
    image: shopfront:latest
    restart: always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

  payment:
    image: payment:latest
    restart: always

#volumes:
#  postgres_data:

networks:
  test: