services:
  shopfront:
    image: shopfront:latest
    restart: always
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432

  payment:
    image: payment:latest
    restart: always
